export const predefinedSkills: string[] = [
  'Node.js',
  'Express.js',
  'NestJS',
  'Spring Boot',
  'Spring Framework',
  'Java EE (Jakarta EE)',
  'Hibernate ORM',
  'Django',
  'Flask',
  'FastAPI',
  'Ruby on Rails',
  'Laravel',
  'ASP.NET Core',
  'Go (Golang)',
  'Gin (Go framework)',
  'Elixir (Phoenix)',
  'C# (.NET Framework)',
  'MongoDB',
  'PostgreSQL',
  'Redis',
];
