name: Deploy to Ubuntu VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # adjust based on your app requirements

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy to Ubuntu VM via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /home/azureuser/pagers
            git pull origin master
            npm install --production
            npm run build
            pm2 reload pagers-app
